# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Fitur10' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fitur10
  pod 'IHKeyboardAvoiding'
  pod 'BottomPopup'
  pod 'SwiftyContacts'
end

